name: Test a branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description:  Branch to test
        required: true
        default: "main"
        
permissions:
  contents: read

concurrency:
  group: test-${{github.event.inputs.branch}} 
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chosen branch
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.inputs.branch}}
          fetch-depth: 0
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm 

      - name: Enable corepack
        run: corepack enable

      - name: Install 
        run: npm install

      - name: Run tests
        run: npm run test:unit

      - name: Integration tests
        run: npm run test
